version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "8976:27017"
    networks:
      - mongo-net
  worker:
    build: ./worker
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    networks: 
      - mongo-net
  processor:
    build: ./processor
    ports:
      - "5001:5000"
    depends_on:
      - "mongo"
    networks: 
      - mongo-net
  app:
    build: .
    ports:
      - "6123:6123"
    depends_on:
      - "mongo"
    networks:
      - mongo-net
networks:
  mongo-net: