data_producer:
  build: './data_producer'
  depends_on:
    - "{{ingestion}}"
  environment:
    - KAFKA_HOST=kafka
    - KAFKA_PORT=9092
    - DATA_DIR=/app/data
  networks:
    - connections
