spark-master:
  build: ./analysis/spark/spark-master
  container_name: spark-master
  shm_size: '2gb'
  ports:
    - "8080:8080"
    - "7077:7077"
  environment:
    - "constraint:node==<yourmasternode>"
  restart: always
  networks:
    connections:
      ipv4_address: 172.24.0.13
spark-worker-1:
  build: ./analysis/spark/spark-worker
  container_name: spark-worker-1
  shm_size: '2gb'
  restart: always
  depends_on:
    - spark-master
  ports:
    - "8081:8081"
  environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==<yourworkernode>"
  networks:
    connections:
      ipv4_address: 172.24.0.14
zeppelin:
  build: ./analysis/zeppelin
  container_name: zeppelin
  restart: always
  shm_size: '2gb'
  ports:
    - "8090:8080"
    - "4040:4040"
    - "40123:40123/udp"
    - "49876:49876/udp"
  networks:
    - connections
  volumes:
    - ./analysis/zeppelin/notebooks:/zeppelin/notebook
  networks:
    connections:
      ipv4_address: 172.24.0.15
analyzer:
  build: ./analysis/app
  container_name: analyzer
  restart: always
  networks:
    - connections
